name: Cleanup Old Images
on:
  schedule:
    - cron: "19 3 1 * *" # 03:19 UTC 1st of every month
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: minus-one
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
